from fpdf import FPDF
import datetime
import os
import config

class PDFReport(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 15)
        self.cell(0, 10, "Weld Quality Inspection Report", align="C")
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, "Generated by Weld Defect Analytics | ISO 5817 Level C | L&T Analytics Demo", align="C")

def generate_pdf_report(results, severity, standard_path, defective_path, output_path):
    """
    Generates a PDF report containing findings, side-by-side images, and a final verdict.
    """
    pdf = PDFReport()
    pdf.add_page()
    
    # Metadata
    pdf.set_font("helvetica", size=10)
    pdf.cell(0, 6, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    pdf.ln(6)
    pdf.cell(0, 6, "Standard used: ISO 5817 Level C")
    pdf.ln(6)
    pdf.cell(0, 6, f"Standard Image: {os.path.basename(standard_path)}")
    pdf.ln(6)
    pdf.cell(0, 6, f"Defective Image: {os.path.basename(defective_path)}")
    pdf.ln(10)
    
    # Image placeholders (Side-by-side)
    img_w = 85
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(img_w, 6, "Standard Weld", align="C")
    pdf.cell(10, 6, "")
    pdf.cell(img_w, 6, "Defective Weld (Annotated)", align="C")
    pdf.ln(8)
    
    y_before_img = pdf.get_y()
    
    # Attempt to load images (will skip if file is missing/unreadable)
    try:
        pdf.image(standard_path, x=pdf.get_x(), y=y_before_img, w=img_w)
    except Exception as e:
        pdf.cell(img_w, 30, f"[Image not found]")
        
    try:
        pdf.image(defective_path, x=pdf.get_x() + img_w + 10, y=y_before_img, w=img_w)
    except Exception as e:
        pass
        
    pdf.set_y(y_before_img + 70)
    
    # Defect Analysis Table
    pdf.set_font("helvetica", "B", 10)
    col_widths = [40, 25, 35, 45, 35]
    headers = ["Defect Type", "Detected", "Value", "Limit", "Severity"]
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 8, h, border=1, align="C")
    pdf.ln()
    
    pdf.set_font("helvetica", "", 10)
    
    def add_row(type_str, detected_str, val_str, limit_str, sev_str):
        pdf.cell(col_widths[0], 8, type_str, border=1)
        pdf.cell(col_widths[1], 8, detected_str, border=1, align="C")
        pdf.cell(col_widths[2], 8, val_str, border=1, align="C")
        pdf.cell(col_widths[3], 8, limit_str, border=1, align="C")
        
        # Color coding for severity
        if sev_str == config.SEVERITY_ACCEPT:
            pdf.set_text_color(0, 150, 0)
        elif sev_str == config.SEVERITY_MARGINAL:
            pdf.set_text_color(200, 150, 0)
        elif sev_str == config.SEVERITY_REJECT:
            pdf.set_text_color(200, 0, 0)
            
        pdf.cell(col_widths[4], 8, sev_str, border=1, align="C")
        pdf.set_text_color(0, 0, 0) # reset
        pdf.ln()
        
    # Populate rows
    p_res = results['porosity']
    p_sev = severity['individual']['porosity']
    add_row("Porosity", "Yes" if p_res['count'] > 0 else "No", 
            f"{p_res['area_percentage']:.2f}%", 
            f"{config.ISO5817LevelC.POROSITY_MAX_AREA_PERCENTAGE}%", p_sev)
    
    u_res = results['undercut']
    u_sev = severity['individual']['undercut']
    add_row("Undercut", "Yes" if u_res['detected'] else "No", 
            f"{u_res['depth_estimate']:.3f}", 
            f"{config.ISO5817LevelC.UNDERCUT_MAX_DEPTH_RATIO}", u_sev)
    
    c_res = results['crack']
    c_sev = severity['individual']['crack']
    add_row("Cracks", "Yes" if c_res['crack_count'] > 0 else "No", 
            f"{c_res['crack_count']}", 
            f"{config.ISO5817LevelC.CRACK_TOLERANCE}", c_sev)
    
    s_res = results['spatter']
    s_sev = severity['individual']['spatter']
    add_row("Spatter", "Yes" if s_res['count'] > 0 else "No", 
            f"{s_res['count']}", 
            f"{config.ISO5817LevelC.SPATTER_MAX_COUNT_PER_100MM}", s_sev)
    
    pdf.ln(10)
    
    # SSIM Score Section
    ssim = results['ssim_score']
    if ssim > 0.9:
        interp = "minor difference"
    elif ssim >= 0.7:
        interp = "moderate difference"
    else:
        interp = "significant difference"
        
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 8, f"Structural Similarity Index (SSIM): {ssim:.4f} ({interp})")
    pdf.ln(10)
    
    # Final Verdict Section
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Final Verdict:")
    pdf.ln(10)
    
    overall = severity['overall']
    if overall == config.SEVERITY_ACCEPT:
        pdf.set_fill_color(200, 255, 200) # light green
        pdf.set_text_color(0, 100, 0)
    elif overall == config.SEVERITY_MARGINAL:
        pdf.set_fill_color(255, 255, 200) # light yellow
        pdf.set_text_color(150, 150, 0)
    else:
        pdf.set_fill_color(255, 200, 200) # light red
        pdf.set_text_color(150, 0, 0)
        
    pdf.set_font("helvetica", "B", 20)
    pdf.cell(0, 20, overall, border=1, align="C", fill=True)
    
    # Output file
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
